version: '3.6'
services:
    web1:
        image: arques/helloworld:latest
        container_name: helloworld
        environment:
          - who=ArquesDev
        ports:
          - 8080:5000
        command: nohup python -u /app/app.py        
    web2:
        image: arques/helloworld:latest
        container_name: hellotech
        environment: 
          - who=ArquesTech
        ports:
          - 8081:5000
        command: nohup python -u /app/app.py